config/routes.rb
Cadastro::Application.routes.draw do

  devise_for :admins, :controllers => {:sessions => 'sessions'}
  devise_scope :admin do
    get "/admin" => 'devise/sessions#new', :as => :new_admin_session
    delete "/logoutadmin" => "devise/sessions#destroy", :as => :destroy_admin_session
  end

  namespace :admin do
    resources :republicas do
      resources :moradores
      resources :atributos
      resources :exmoradores
      put 'approve'
      put 'disapprove'
      get "statistics"
      get 'send_reconfirmation'
    end
    resources :dashboard, except: [:show, :edit, :new, :update, :destroy]

    namespace :dashboard do
      get 'listadereps'
    end

    resources :categorias
    resources :servicos do
      resources :comentarios, only: [:index, :edit, :destroy]
    end

    resources :eventos do
      resources :evento_moradores do
        collection do
          get 'add_moradores'
          get 'add_exmoradores'
        end
      end
    end
    resources :modalidades
  end

  devise_for :republicas, :controllers => {:registrations => 'registrations'}
  devise_scope :republica do
    get "/login" => "devise/sessions#new", :as => :new_republica_session 
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_republica_session
  end

  get "sistema/index"
  
  resources :republicas, except: [:edit, :update] do
    resources :exmoradores, only: [:index, :new, :create]
    get 'moradores/edit', to: 'moradores#edit'
    put 'moradores', to: 'moradores#update'
    resources :moradores, except: [:show, :edit, :update]
    resource :contato, only: [:edit, :update]
    resource :social_information, only: [:edit, :update]
    resource :vaga, only: [:update]
    resources :eventos, except: [:index]
  end

  namespace :republicas do
    put 'send_reconfirmation'
  end

  get "/terms" => "sistema#terms", :as => :terms

  authenticated :user do
    root :to => 'sistema#index'
  end

  resources :eventos, only: [:index]

  resources :categorias
  resources :servicos do
    resources :comentarios, only: [:index, :edit, :new, :create]
  end

  root :to => 'sistema#index'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
	helper_method :sort_column, :sort_direction


	def index
		@republicas = Republica.where(approved: false).page(params[:page]).order(sort_column + ' ' + sort_direction)
		@exmoradores = Morador.is_exmorador.page(params[:page])

		@dashboard_header = true

		@eventos = Evento.where(ano: Time.now.year, open: false)

		respond_to do |format|
	      format.html # index.html.erb
	      format.js
	  end
	end

	def listadereps
		@masculinas = Republica.where(tipo: 'Masculina').order('approved DESC', :nome)
		@femininas = Republica.where(tipo: 'Feminina').order('approved DESC',:nome)
		@mistas = Republica.where(tipo: 'Mista').order('approved DESC',:nome)
	end

	private

	def sort_column
		Republica.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
	end

	def sort_direction
		%w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
	end

end

app/views/admin/dashboard/_last_registrations.html.erb
<table class='table table-condensed republicas'>
	<thead class='republicas-head'>
		<tr>
			<th></th> <!-- Logotipo -->
			<th><%= sortable "nome", "República" %></th>
			<th><%= sortable "tipo" %></th>
			<th><%= sortable "ano_de_fundacao", "Ano de Fundação" %></th>
			<th>Atributos</th> <!-- Prêmios - Campeã de InterReps, Reuniões, etc. -->

			<th><%= sortable "created_at", "Registro" %></th>
			<th><%= sortable "current_sign_in_at", "Último Login" %></th>
			<th>Status de Email</th>
			<th>Estatísticas</th>
			<th></th> <!-- Comandos ADMIN -->
		</tr>
	</thead>

	<tbody>
		<% @republicas.each do |republica| %>
		<tr>
			<td><%= image_tag republica.logotipo_url(:thumb), id: 'logotipo' %></td>
			<td><b><%= link_to republica.nome, admin_republica_path(republica) %></b></td>
			<td><%= republica.tipo %></td>
			<td><%= republica.ano_de_fundacao %></td>
			<td>
				<%  if republica.interreps_vencidos.any? %>
				<i class='fa fa-trophy interreps'></i>
				<% end %>
				<% if republica.presente_reunioes == true %>
				<i class='fa fa-calendar reunioes'></i>
				<% end %>

				<% if false %>
				<%= image_tag 'glyphicons/glyphicons_075_stroller.png', class: 'nova_rep' if Time.now.year - "#{republica.ano_de_fundacao}".to_i <= 1 %>
				<% end %>
			</td>


			<td><%= republica.created_at.to_date %></td>

			<td>
				<% if republica.current_sign_in_at != nil %>
				<%= time_ago_in_words republica.current_sign_in_at %>
				<% end %>
			</td>

			<td>
				<% if republica.confirmed? && !republica.pending_reconfirmation? %>
				<span style='color:green'>OK</span>
				<% elsif republica.confirmed? && republica.pending_reconfirmation? %>
				<span style='color:red'>Precisa Reconfirmar</span>
				<% else %>
				<span style='color:red'>Não Confirmado</span>
				<% end %>

			</td>

			<td>
				<%= link_to 'Statistics', admin_republica_statistics_path(republica), class: 'btn btn-mini' %>
			</td>
				
			<td class='admin_action'>
				<%= link_to 'Editar', edit_admin_republica_path(republica), class: 'btn btn-mini' %>
				<%= link_to 'Deletar', republica, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-mini' %>
				<% if republica.approved == false %>
				<%= link_to 'Approve', admin_republica_approve_path(republica), method: :put, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-success btn-mini' %>
				<% end %>
				<% if republica.approved == true %>
				<%= link_to 'Disapprove', admin_republica_disapprove_path(republica), method: :put, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-warning btn-mini' %>
				<% end %>
			</td>

		</tr>
		<% end %>
	</tbody>
</table>


<p><%= will_paginate @republicas %></p>

app/views/admin/dashboard/_year_events.html.erb
<% @eventos.sort_by(&:created_at).each do |ev| %>
<div class='content-box-for-table'>
	<table class='table table-condensed'>
	    <thead>
	        <tr>
	            <th>Nome</th>
	            <th>Ano</th>
	            <th>Total Repúblicas</th>
	            <th>Total Jogadores</th>
	            <th></th>

	        </tr>
	    </thead>

		    <tbody>
				<tr>
				    <td>
				        <%= ev.nome %>
				    </td>
				    <td><%= ev.ano %></td>
				    <td><%= ev.republicas.count  %> </td>
				    <td><%= ev.jogadores.count  %> </td>
				    <td>
				    	<% if !ev.open %>
				        	<%= link_to "Gerar Relatório Final", admin_evento_evento_moradores_path(ev), class: 'btn btn-small btn-success admin_action' %>
				        <% end %>
				    </td>
				</tr>

			</tbody>
	</table>

</div>
<% end %>

app/views/admin/dashboard/index.html.erb
<h2><i class='fa fa-gears'></i> Utilidades</h2>
<%= link_to 'Gerar lista de Repúblicas', admin_dashboard_listadereps_path, class: 'nav-btn nav-btn-a' %>
<hr>

<h2>Últimos Cadastros</h2>
<div id='republicas' class='content-box-for-table'><%= render 'last_registrations' %></div>

<h2>Eventos do Ano</h2>
<%= render 'year_events' %>

app/views/admin/dashboard/index.js.erb
$("#republicas").html("<%=j render 'last_registrations' %>");
$(".pagination a").attr('data-remote', true);

app/views/admin/dashboard/listadereps.html.erb
<h2>Masculinas</h2>
<div class='content-box content-box-for-table'>
<table class='table table-condensed'>
	<thead>
		<tr>
			<th style='text-align:left'>Nome</th>
			<th>Tipo</th>
			<th>Approved</th>
			<th style='text-align:left'>Moradores</th>
		</tr>
	</thead>

	<tbody>
		<% @masculinas.each do |rep| %>
		<tr>
			<td style='text-align:left'>
				<%= rep.nome %>
			</td>
			<td><%= rep.tipo %></td>
			<td><% if rep.approved %>
				<%= 'Sim' %>
				<% else %>
				<%= 'Não' %>
				<% end %>
			</td>
			<td style='text-align:left'><% rep.moradores.atual.order(:nome).each do |morador| %>
				<%= morador.nome + ' ' + morador.sobrenome %>
				<br>
				<% end %>
			</td>
			<% end %>
		</tbody>
	</table>
</div>
	<br />

	<h2>Femininas</h2>

<div class='content-box content-box-for-table'>
	<table class='table table-condensed'>
		<thead>
			<tr>
				<th style='text-align:left'>Nome</th>
				<th>Tipo</th>
				<th>Approved</th>
				<th style='text-align:left'>Moradores</th>
			</tr>
		</thead>

		<tbody>
			<% @femininas.each do |rep| %>
			<tr>
				<td style='text-align:left'>
					<%= rep.nome %>
				</td>
				<td><%= rep.tipo %></td>
				<td><% if rep.approved %>
					<%= 'Sim' %>
					<% else %>
					<%= 'Não' %>
					<% end %>
				</td>
				<td style='text-align:left'><% rep.moradores.atual.order(:nome).each do |morador| %>
					<%= morador.nome + ' ' + morador.sobrenome %>
					<br>
					<% end %>
				</td>
				<% end %>
			</tbody>
		</table>
</div>

		<br />

		<h2>Mistas</h2>

<div class='content-box content-box-for-table'>
		<table class='table table-condensed'>
			<thead>
				<tr>
					<th style='text-align:left'>Nome</th>
					<th>Tipo</th>
					<th>Approved</th>
					<th style='text-align:left'>Moradores</th>
				</tr>
			</thead>

			<tbody>
				<% @mistas.each do |rep| %>
				<tr>
					<td style='text-align:left'>
						<%= rep.nome %>
					</td>
					<td><%= rep.tipo %></td>
					<td><% if rep.approved %>
						<%= 'Sim' %>
						<% else %>
						<%= 'Não' %>
						<% end %>
					</td>
					<td style='text-align:left'><% rep.moradores.atual.order(:nome).each do |morador| %>
						<%= morador.nome + ' ' + morador.sobrenome %>
						<br>
						<% end %>
					</td>
					<% end %>
				</tbody>
			</table>
			</div>

			<br />