config/routes.rb
Cadastro::Application.routes.draw do

  devise_for :admins, :controllers => {:sessions => 'sessions'}
  devise_scope :admin do
    get "/admin" => 'devise/sessions#new', :as => :new_admin_session
    delete "/logoutadmin" => "devise/sessions#destroy", :as => :destroy_admin_session
  end

  namespace :admin do
    resources :republicas do
      resources :moradores
      resources :atributos
      resources :exmoradores
      put 'approve'
      put 'disapprove'
      get "statistics"
      get 'send_reconfirmation'
    end
    resources :dashboard, except: [:show, :edit, :new, :update, :destroy]

    namespace :dashboard do
      get 'listadereps'
    end

    resources :categorias
    resources :servicos do
      resources :comentarios, only: [:index, :edit, :destroy]
    end

    resources :eventos do
      resources :evento_moradores do
        collection do
          get 'add_moradores'
          get 'add_exmoradores'
        end
      end
    end
    resources :modalidades
  end

  devise_for :republicas, :controllers => {:registrations => 'registrations'}
  devise_scope :republica do
    get "/login" => "devise/sessions#new", :as => :new_republica_session 
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_republica_session
  end

  get "sistema/index"
  
  resources :republicas, except: [:edit, :update] do
    resources :exmoradores, only: [:index, :new, :create]
    get 'moradores/edit', to: 'moradores#edit'
    put 'moradores', to: 'moradores#update'
    resources :moradores, except: [:show, :edit, :update]
    resource :contato, only: [:edit, :update]
    resource :social_information, only: [:edit, :update]
    resource :vaga, only: [:update]
    resources :eventos, except: [:index]
  end

  namespace :republicas do
    put 'send_reconfirmation'
  end

  get "/terms" => "sistema#terms", :as => :terms

  authenticated :user do
    root :to => 'sistema#index'
  end

  resources :eventos, only: [:index]

  resources :categorias
  resources :servicos do
    resources :comentarios, only: [:index, :edit, :new, :create]
  end

  root :to => 'sistema#index'

end

app/views/layouts/admin/_admin_navigation.html.erb
<div class='row-fluid'>
	<div class='span3'>
		<div class='pull-left'>
			<%= link_to image_tag('logo-navyblue.png'), root_path %>
		</div>
	</div>

	<div class='span9'>

		<nav class='nav--site'>
			<ul class="nav--links pull-right">

				<li>
					<%= link_to "Repúblicas", admin_republicas_path %>
				</li>

				<li><a href='http://republicasunicamp.com.br/contato/' target='_blank'>Contato</a></li>

				<li>
					<%= link_to('Logout', destroy_admin_session_path, :method=>'delete') %>
				</li>

			</ul>
		</nav>

	</div>
</div>

app/views/layouts/admin/_dashboard.html.erb
<header class='jumbotron subhead dashboard'>
<div class='container'>
	<h1>Admin Dashboard</h1>
	<p>Edição e funções do administrador.</p>
	</div>
</header>

app/views/layouts/admin/_eventos.html.erb
<header class='jumbotron subhead'>
	<div class='container'>
		<h1>Eventos</h1>
		<p>Crie e edite eventos.</p>
		<%= link_to 'Adicionar Evento' , new_admin_evento_path, class: 'nav-btn nav-btn-c' %>
		<%= link_to 'Ver Modalidades' , admin_modalidades_path, class: 'nav-btn nav-btn-a' %>
	</div>

</header>

app/views/layouts/admin/_modalidades.html.erb
<header class='jumbotron subhead'>
	<div class='container'>
		<h1>Modalidades</h1>
		<p>Crie e edite modalidades.</p>
		<%= link_to 'Criar Modalidade' , new_admin_modalidade_path, class: 'nav-btn nav-btn-c' %>
		<%= link_to 'Ver Eventos' , admin_eventos_path, class: 'nav-btn nav-btn-a' %>
	</div>

</header>

app/views/layouts/admin/_nav-sub.html.erb
<div class="nav--sub" id="account-navigation">
	<ul class='nav--links'>
		<li class="<%= 'active' if current_page?(admin_dashboard_index_path) %>">
			<%= link_to "Dashboard", admin_dashboard_index_path %>
		</li>
		<li class="<%= 'active' if current_page?(admin_republicas_path) %>">
			<%= link_to "Repúblicas", admin_republicas_path %>
		</li>

		<li class="<%= 'active' if current_page?(admin_eventos_path) %>">
			<%= link_to 'Eventos', admin_eventos_path %>
		</li>

		<li class="<%= 'active' if current_page?(admin_servicos_path) %>">
			<%= link_to 'Serviços', admin_servicos_path %>
		</li>

		<li class='nav--text pull-right'><span>Logado como <%= link_to 'Admin', admin_dashboard_index_path %></span></li>
	</ul>
</div>

app/views/layouts/admin/_servicos.html.erb
<header class='jumbotron subhead'>
	<div class='container'>
		<h1>Serviços</h1>
		<p>Aqui você poderá adicionar e ver as recomendações de serviços de outras Repúblicas.</p>
		<%= link_to 'Ver Categorias', admin_categorias_path, class: 'nav-btn nav-btn-a' %>
	</div>

</header>