config/routes.rb
Cadastro::Application.routes.draw do

  devise_for :admins, :controllers => {:sessions => 'sessions'}
  devise_scope :admin do
    get "/admin" => 'devise/sessions#new', :as => :new_admin_session
    delete "/logoutadmin" => "devise/sessions#destroy", :as => :destroy_admin_session
  end

  namespace :admin do
    resources :republicas do
      resources :moradores
      resources :atributos
      resources :exmoradores
      put 'approve'
      put 'disapprove'
      get "statistics"
      get 'send_reconfirmation'
    end
    resources :dashboard, except: [:show, :edit, :new, :update, :destroy]

    namespace :dashboard do
      get 'listadereps'
    end

    resources :categorias
    resources :servicos do
      resources :comentarios, only: [:index, :edit, :destroy]
    end

    resources :eventos do
      resources :evento_moradores do
        collection do
          get 'add_moradores'
          get 'add_exmoradores'
        end
      end
    end
    resources :modalidades
  end

  devise_for :republicas, :controllers => {:registrations => 'registrations'}
  devise_scope :republica do
    get "/login" => "devise/sessions#new", :as => :new_republica_session 
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_republica_session
  end

  get "sistema/index"
  
  resources :republicas, except: [:edit, :update] do
    resources :exmoradores, only: [:index, :new, :create]
    get 'moradores/edit', to: 'moradores#edit'
    put 'moradores', to: 'moradores#update'
    resources :moradores, except: [:show, :edit, :update]
    resource :contato, only: [:edit, :update]
    resource :social_information, only: [:edit, :update]
    resource :vaga, only: [:update]
    resources :eventos, except: [:index]
  end

  namespace :republicas do
    put 'send_reconfirmation'
  end

  get "/terms" => "sistema#terms", :as => :terms

  authenticated :user do
    root :to => 'sistema#index'
  end

  resources :eventos, only: [:index]

  resources :categorias
  resources :servicos do
    resources :comentarios, only: [:index, :edit, :new, :create]
  end

  root :to => 'sistema#index'

end

app/models/evento.rb
#encoding: utf-8
class Evento < ActiveRecord::Base
  has_many :evento_modalidades, dependent: :destroy
  has_many :modalidades, through: :evento_modalidades

  # Condicoes para retornar apenas moradores
  has_many :evento_moradores, dependent: :destroy, :conditions => {type_of_player: false}
  has_many :moradores, through: :evento_moradores, :conditions => "evento_moradores.type_of_player = 'false'"

  # Condicoes para retornar apenas ex-moradores
  # Salva jogador como type_of_player = true para indicar ex-morador
  has_many :evento_exmoradores, class_name: "EventoMorador", source: :evento_morador, dependent: :destroy, :conditions => {type_of_player: true}
  has_many :exmoradores, class_name: "Morador", source: :morador, through: :evento_exmoradores, :conditions => "evento_moradores.type_of_player = 'true'"

  # Condicoes para retornar TODOS os JOGADORES
  has_many :evento_jogadores, class_name: "EventoMorador", dependent: :destroy, source: :evento_morador
  has_many :jogadores, class_name: "Morador", source: :morador, through: :evento_jogadores

  # has_many :jogadores, through: :evento_exmoradores do
  #  def all_moradores
  #      where("moradores.exmorador = ? OR moradores.exmorador = ?", "f", "t")
  #  end
 # end

  has_many :evento_republicas, dependent: :destroy, inverse_of: :evento
  has_many :republicas, through: :evento_republicas

  has_many :republica_evento_modalidades, through: :evento_modalidades

  accepts_nested_attributes_for :evento_republicas, :allow_destroy => true, :reject_if => :reject_empty_opcao_agregado

  attr_accessible :ano, :nome, :open, :max1_ex, :max1_ag, :max2_ex, :max2_ag
  attr_accessible :modalidade_ids, :morador_ids, :republicas, :evento_republicas_attributes, :exmorador_ids
  attr_accessor :opcao_exag
  attr_accessible :opcao_exag
  attr_accessor :play_mods_ids
  attr_accessible :play_mods_ids
  attr_accessible :terms_of_service
  attr_accessible :terms_text

  validates :ano, presence: true
  validates :nome, presence: true
  validates :terms_text, presence: true, length: {minimum: 100}
  # validates :nome, uniqueness: {scope: :ano}
  validate :check_uniqueness_name_and_year
  before_create :repeat_old_names
  validates_acceptance_of :terms_of_service, message: "Os termos de inscrição devem ser aceitos."

  def check_uniqueness_name_and_year
    evs = []
    if !self.new_record?
      evs = Evento.where("id != ? AND lower(nome) = ? AND ano = ?", self.id, self.nome.downcase, self.ano)
    elsif self.nome.present? && self.ano.present?
      evs = Evento.where('lower(nome) = ? AND ano = ?', self.nome.downcase, self.ano)
    end

    if evs.any?
      self.errors.add(:base, "Já existe um evento com esse nome e ano.")
    end
  end

  def reject_empty_opcao_agregado(attributes)
    exists = attributes['id'].present?
    empty = attributes[:agregado].blank? && attributes[:opcao].blank?
    attributes.merge!({:_destroy => 1}) if exists and empty
    return (!exists and empty)
  end


  def repeat_old_names
    ev = []
    ev = Evento.where('lower(nome) = ?', self.nome.downcase)

    if ev.any?
      self.nome = ev.first.nome
    end
  end

  def inscrito?(republica)
    if republica.eventos.include?(self)
      return true
    else
      return false
    end
  end

  def cancelar_inscricao(republica)
    # Deletar Moradores Inscritos
    moradores_ids = republica.moradores.collect(&:id)
    exmoradores_ids = republica.exmoradores.collect(&:id)
    todos_ids = moradores_ids + exmoradores_ids

    Evento.transaction do

      self.evento_jogadores.where(morador_id: todos_ids).destroy_all

      # Deletar Agregados Inscritos
      self.evento_republicas.where(republica_id: republica.id).destroy_all

      # Deletar Modalidades Inscritas
      self.republica_evento_modalidades.where(republica_id: republica.id).destroy_all
    end

    return true
  end

end

app/controllers/admin/eventos_controller.rb
#encoding: utf-8

class Admin::EventosController < AdminController

	def index
		@eventos_header = true
		@eventos = Evento.order("ano DESC")

		respond_to do |format|
			format.html
			format.json { render json: @eventos }
		end
	end

	def new
		@evento = Evento.new
		@modalidades = Modalidade.all.group_by{ |d| d[:tipo]}

		respond_to do |format|
      		format.html # new.html.erb
      		format.json { render json: @evento }
 	 	end
	end

	def edit
		@evento = Evento.find(params[:id])
		@modalidades = Modalidade.all.group_by{ |d| d[:tipo]}
	end

	def create
	params[:evento][:modalidade_ids].reject! { |c| c.empty? } if params[:evento][:modalidade_ids].present?
    @evento = Evento.new(params[:evento])
    @modalidades = Modalidade.all.group_by{ |d| d[:tipo]}


        respond_to do |format|
	      if @evento.save
	        format.html { redirect_to admin_eventos_path, notice: 'Novo evento criado com sucesso!' }
	        format.json { render json: @evento, status: :created, location: @evento }
	      else
	        format.html { render action: "new" }
	        format.json { render json: @evento.errors, status: :unprocessable_entity }
          end
        end
    end

	def update
		@evento = Evento.find(params[:id])
		@modalidades = Modalidade.all.group_by{ |d| d[:tipo]}

		respond_to do |format|
			if @evento.update_attributes(params[:evento])
				format.html { redirect_to admin_eventos_path, notice: 'Evento foi atualizado com sucesso.' }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @evento.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@evento = Evento.find(params[:id])

		respond_to do |format|
			if @evento.destroy
				format.html { redirect_to admin_eventos_path, notice: 'Evento deletado!' }
				format.json { head :no_content }
			else
				format.html { redirect_to admin_eventos_path, :alert => "O evento não pode ser deletado."  }
				format.json { render json: @evento.errors, status: :unprocessable_entity }
			end
		end
	end


end

app/controllers/eventos_controller.rb
#encoding: utf-8

class EventosController < RepublicaController

  def index
    authorize! :index, Evento
    @eventos_header = true
    @eventos = Evento.order("ano DESC")

    respond_to do |format|
      format.html
      format.json { render json: @eventos }
    end
  end

  def new
    @evento = Evento.new
    @modalidades = Modalidade.all.group_by{ |d| d[:tipo]}

    respond_to do |format|
          format.html # new.html.erb
          format.json { render json: @evento }
    end
  end

  def show
    @republica = current_republica
    @evento = Evento.find(params[:id])
    authorize! :show, @evento
    render :layout => "show"
  end

  def edit
    @republica = current_republica
    @evento = Evento.find(params[:id])
    authorize! :edit, @evento

    @modalidades = @evento.modalidades.group_by{ |d| d[:tipo]}

    # Seleciona somente os ex-moradores que podem jogar
    # No caso do InterReps
    @exmoradores_ajogar = find_exmoradores_aptos(@evento, @republica)

    # Cria numero de agregados que podem ser inscritos
    @agregados = @evento.evento_republicas.find_with_agregados(current_republica)
    max_ag = [@evento.max1_ag, @evento.max2_ag].max
    (max_ag - @agregados.count).times do |i|
      @agregados << @evento.evento_republicas.build
    end
  end

  # def create
  #   params[:evento][:modalidade_ids].reject! { |c| c.empty? }
  #   @evento = Evento.new(params[:evento])

  #       respond_to do |format|
  #       if @evento.save
  #         format.html { redirect_to eventos_path, notice: 'Novo evento criado com sucesso!' }
  #         format.json { render json: @evento, status: :created, location: @evento }
  #       else
  #         format.html { render action: "new" }
  #         format.json { render json: @evento.errors, status: :unprocessable_entity }
  #         end
  #       end
  #   end

  def update
    @republica = current_republica
    @evento = Evento.find(params[:id])
    @modalidades = @evento.modalidades.group_by{ |d| d[:tipo]}

    error = false
    # So faz verificacoes se houver valores positivios
    if [@evento.max1_ex, @evento.max1_ag, @evento.max2_ex, @evento.max2_ag].max != 0
      error = check_number_exmoradores_agregados(params[:evento], @evento)
    end

    # Checa numero de moradores
    error = check_number_moradores(params[:evento], @evento) || error

    respond_to do |format|
      if updates_all_subelements(error, @evento, params[:evento])
        format.html { redirect_to eventos_path, notice: 'Inscrição efetuada com sucesso.' }
        format.json { head :no_content }
      else
        # Seleciona somente os ex-moradores que podem jogar
        # No caso do InterReps
        @exmoradores_ajogar = find_exmoradores_aptos(@evento, @republica)

            # raise error

          # Cria numero de agregados que podem ser inscritos
          @agregados = @evento.evento_republicas.find_with_agregados(current_republica)
          max_ag = [@evento.max1_ag, @evento.max2_ag].max

          if max_ag != 0
            lista = params[:evento][:evento_republicas_attributes]
            lista = lista.drop(1)
            (max_ag - @agregados.count).times do |i|
              @agregados << @evento.evento_republicas.build(agregado: lista.first.last.try(:[],:agregado))
              lista = lista.drop(1)
            end
          end
        format.html { render action: "edit" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @evento = Evento.find(params[:id])
    authorize! :destroy, @evento

    respond_to do |format|
      if destroy_modalidades(@evento) && @evento.cancelar_inscricao(current_republica)
        format.html { redirect_to eventos_path, notice: 'Inscrição Cancelada!' }
        format.json { head :no_content }
      else
        format.html { redirect_to eventos_path, :alert => "A inscrição não pôde ser cancelada."  }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  def check_number_exmoradores_agregados(params, evento)
    opcao_exag = params[:evento_republicas_attributes].first.last[:opcao]
    exmorador_ids = params[:exmorador_ids]
    exmorador_ids.reject!(&:empty?) if exmorador_ids.present?

    # raise error

    # Se houver agregados nas opcoes
    p = params[:evento_republicas_attributes].drop(1)
    count = 0
    if evento.max1_ag != 0 || evento.max2_ag != 0
     p.each do |id, a|
        if !a[:agregado].empty?
          count += 1
        end
      end
    end
    if opcao_exag == '1'
      if exmorador_ids.present? && (exmorador_ids.size > evento.max1_ex)
        evento.errors.add(:base, "Você só pode escolher no máximo #{evento.max1_ex} ex-moradores")
      end
      if count > evento.max1_ag
        evento.errors.add(:base, "Você só pode escolher no máximo #{evento.max1_ag} agregados")
      end

    elsif opcao_exag == '2'
      if exmorador_ids.present? && (exmorador_ids.size > evento.max2_ex)
        evento.errors.add(:base, "Você só pode escolher no máximo #{evento.max2_ex} ex-moradores")
      end

      if count > evento.max2_ag
        evento.errors.add(:base, "Você só pode escolher no máximo #{evento.max2_ag} agregados")
      end

    else
      evento.errors.add(:base, "Você deve escolher uma das opções")
    end

    return true if evento.errors.present?
    return false

  end

  def check_number_moradores(params, evento)
    morador_ids = params[:morador_ids]
    morador_ids.reject!(&:empty?)

    if morador_ids.size == 0
      evento.errors.add(:base, "Você deve escolher ao menos 1 morador")
      return true
    end

    return false
  end

  def inscreve_modalidades(params, evento)
    play_mods = params[:play_mods_ids].reject(&:empty?)

    # devolve erro se não houver modalidades escolhidas
    if play_mods.empty?
      evento.errors.add(:base, "Você deve escolher pelo menos 1 modalidade")
      return false
    end

    disponiveis_id = evento.evento_modalidades.collect(&:id) # Todos evento_modalidades disponiveis pra esse evento

    remover = disponiveis_id - play_mods

    Evento.transaction do
      # Remove todas as outras modalidades que nao foram escolhidas
      RepublicaEventoModalidade.where(republica_id: current_republica.id, evento_modalidade_id: remover).destroy_all

      # Cria se nao existir
      play_mods.each do |id|
        RepublicaEventoModalidade.where(republica_id: current_republica.id, evento_modalidade_id: id).first_or_create!
      end
    end

    return true
  end

  def updates_all_subelements(error, evento, params)
    # Tenta inscrever modalidades
    result = false
    Evento.transaction do
      if evento.modalidades.any?
        inscritas = inscreve_modalidades(params, evento)
      else
        inscritas = true
      end

      result = (error == false && inscritas == true && evento.update_attributes(params))

      if inscritas != true
        raise ActiveRecord::Rollback
        return false
      end
    end

    return result
  end

  def destroy_modalidades(evento)
    disponiveis_id = evento.evento_modalidades.collect(&:id) # Todos evento_modalidades disponiveis pra esse evento

    Evento.transaction do
      # Remove todas as modalidades para essa republica nesse evento
      RepublicaEventoModalidade.where(republica_id: current_republica.id, evento_modalidade_id: disponiveis_id).destroy_all
    end

    return true
  end

  def find_exmoradores_aptos(evento, republica)
    if evento.nome.downcase == "interreps"
      exmoradores = republica.exmoradores
      # Retorna interreps anteriores ao atual com seus moradores que jogaram
      eventos = Evento.joins(:evento_moradores).where("lower(nome) = 'interreps' AND ano < ?", evento.ano).uniq

      # Busca todos os morador_ids desses eventos
      jogador_ids = eventos.map(&:evento_moradores).flatten.map(&:morador_id)

      # Seleciona exmoradores que podem jogar
      exmoradores_ajogar = exmoradores.where(id: jogador_ids)

      return exmoradores_ajogar
    end
  end

end

app/views/admin/eventos/_eventos_box.html.erb
<tr>
    <td>
        <%= ev.nome %>
    </td>
    <td><%= ev.ano %></td>

    <td>
        <%= link_to 'Adicionar', add_moradores_admin_evento_evento_moradores_path(ev), class: 'btn btn-mini btn-success' %>
    </td>

    <td>
        <%= link_to 'Adicionar', add_exmoradores_admin_evento_evento_moradores_path(ev), class: 'btn btn-mini btn-success' %>
    </td>

    <td class='admin_action'>

        <% if !ev.open %>
        	<%= link_to "Abrir para Inscrições", admin_evento_path(ev, :evento => {open: 'true' } ), method: :put, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-mini btn-info admin_action' %>
        <% else %>
        	<%= link_to "Fechar Inscrições", admin_evento_path(ev, :evento => {open: 'false' } ), method: :put, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-mini btn-warning admin_action' %>
        <% end %>
       <%= link_to "<i class='icon-edit'></i>".html_safe, edit_admin_evento_path(ev), class: 'btn btn-mini admin_action' %>
        <%= link_to "<i class='icon-trash icon-white' ></i>".html_safe, admin_evento_path(ev), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger btn-mini admin_action' %>
    </td>
</tr>

app/views/admin/eventos/edit.html.erb
<div class='content-box center-form'>

	<%= simple_form_for [:admin, @evento], validate: true, html: {id: 'republica_form', multipart: true} do |f| %>
	<%= f.error_notification %>
	<%= display_base_errors @evento %>


	<fieldset id='evento'>
		<legend>Evento</legend>
		<%= f.input :nome, placeholder: 'Nome', label: false, input_html: {class: 'nome'}  %>
		<%= f.input :ano, label: false, placeholder: 'Ano' %>

		<p class="text-info">Selecione o número máximo de ex-moradores e agregados que poderão ser inscritos. Por exemplo: 2 ex-moradores e 1 agregado.</p>

		<%= f.input :max1_ex, wrapper: :inline, label: 'Ex-Moradores' %>
		<%= f.input :max1_ag, wrapper: :inline, label: 'Agregados' %>

		<p class="text-info">Insira aqui a segunda opção para as inscrições. Por exemplo: nenhum ex-morador e 2 agregados.</p>

		<%= f.input :max2_ex, wrapper: :inline, label: 'Ex-Moradores' %>
		<%= f.input :max2_ag, wrapper: :inline, label: 'Agregados' %>


		<legend>Modalidades</legend>
		<% @modalidades.try(:each) do |tipo, mod| %>
			<span class="label label-info"><%= tipo + "s" %></span>
	    	<%= f.association :modalidades, collection: mod, label: false, label_method: :nome, as: :check_boxes %>
	    <% end %>

	   	<legend>Termos de Inscrição</legend>
	    <%= f.input :terms_text, placeholder: 'Termos de inscrição com as regras do evento, casos de reembolso, etc. (mínimo de 100 caracteres)', label: false, input_html: {class: 'input-xxlarge', rows: 10} %>
	</fieldset>

	<div class="form-actions" id='cadastro_actions'>
		<%= f.submit 'Atualizar', class: 'btn btn-primary' %>
		<%= link_to 'Cancel', admin_eventos_path, class: 'btn' %>
	</div>


	<% end %>

</div>

app/views/admin/eventos/index.html.erb
<% @eventos.group_by{|d| d[:nome]}.sort.each do |ev_name, evs| %>
<legend><%= ev_name %></legend>
<div class='content-box-for-table'>
	<table class='table table-condensed'>
	    <thead>
	        <tr>
	            <th>Nome</th>
	            <th>Ano</th>
	            <th>Adicionar Moradores</th>
	            <th>Adicionar Ex-Moradores</th>
	            <th></th>

	        </tr>
	    </thead>

		    <tbody>

			<%= render partial: 'eventos_box', collection: evs, as: :ev %>

			</tbody>
	</table>

</div>
<% end %>

app/views/admin/eventos/new.html.erb
<div class='content-box center-form'>

	<%= simple_form_for [:admin, @evento], validate: true, html: {id: 'republica_form', multipart: true} do |f| %>
	<%= f.error_notification %>
	<%= display_base_errors @evento %> 


	<fieldset id='evento'>
		<legend>Evento</legend>
		<%= f.input :nome, placeholder: 'Nome', label: false, input_html: {class: 'nome'}  %>
		<%= f.input :ano, label: false, placeholder: 'Ano' %>

		<p class="text-info">Selecione o número máximo de ex-moradores e agregados que poderão ser inscritos. Por exemplo: 2 ex-moradores e 1 agregado.</p>

		<%= f.input :max1_ex, wrapper: :inline, label: 'Ex-Moradores' %>
		<%= f.input :max1_ag, wrapper: :inline, label: 'Agregados' %>

		<p class="text-info">Insira aqui a segunda opção para as inscrições. Por exemplo: nenhum ex-morador e 2 agregados.</p>

		<%= f.input :max2_ex, wrapper: :inline, label: 'Ex-Moradores' %>
		<%= f.input :max2_ag, wrapper: :inline, label: 'Agregados' %>


		<legend>Modalidades</legend>
		<% @modalidades.try(:each) do |tipo, mod| %>
			<span class="label label-info"><%= tipo + "s" %></span>
	    	<%= f.association :modalidades, collection: mod, label: false, label_method: :nome, as: :check_boxes %>
	    <% end %>

	    <legend>Termos de Inscrição</legend>
	    <%= f.input :terms_text, placeholder: 'Termos de inscrição com as regras do evento, casos de reembolso, etc. (mínimo de 100 caracteres)', label: false, input_html: {class: 'input-xxlarge', rows: 10} %>
	</fieldset>

	<div class="form-actions" id='cadastro_actions'>
		<%= f.submit 'Criar', class: 'btn btn-primary' %>
		<%= link_to 'Cancel', admin_eventos_path, class: 'btn' %>
	</div>


	<% end %>

</div>