config/routes.rb
Cadastro::Application.routes.draw do

  devise_for :admins, :controllers => {:sessions => 'sessions'}
  devise_scope :admin do
    get "/admin" => 'devise/sessions#new', :as => :new_admin_session
    delete "/logoutadmin" => "devise/sessions#destroy", :as => :destroy_admin_session
  end

  namespace :admin do
    resources :republicas do
      resources :moradores
      resources :atributos
      resources :exmoradores
      put 'approve'
      put 'disapprove'
      get "statistics"
      get 'send_reconfirmation'
    end
    resources :dashboard, except: [:show, :edit, :new, :update, :destroy]

    namespace :dashboard do
      get 'listadereps'
    end

    resources :categorias
    resources :servicos do
      resources :comentarios, only: [:index, :edit, :destroy]
    end

    resources :eventos do
      resources :evento_moradores do
        collection do
          get 'add_moradores'
          get 'add_exmoradores'
        end
      end
    end
    resources :modalidades
  end

  devise_for :republicas, :controllers => {:registrations => 'registrations'}
  devise_scope :republica do
    get "/login" => "devise/sessions#new", :as => :new_republica_session 
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_republica_session
  end

  get "sistema/index"
  
  resources :republicas, except: [:edit, :update] do
    resources :exmoradores, only: [:index, :new, :create]
    get 'moradores/edit', to: 'moradores#edit'
    put 'moradores', to: 'moradores#update'
    resources :moradores, except: [:show, :edit, :update]
    resource :contato, only: [:edit, :update]
    resource :social_information, only: [:edit, :update]
    resource :vaga, only: [:update]
    resources :eventos, except: [:index]
  end

  namespace :republicas do
    put 'send_reconfirmation'
  end

  get "/terms" => "sistema#terms", :as => :terms

  authenticated :user do
    root :to => 'sistema#index'
  end

  resources :eventos, only: [:index]

  resources :categorias
  resources :servicos do
    resources :comentarios, only: [:index, :edit, :new, :create]
  end

  root :to => 'sistema#index'

end

app/models/servico.rb
#encoding: utf-8

class Servico < ActiveRecord::Base
	self.per_page = 5
	before_save :titleize_endereco
	before_validation :downcase_site
	before_destroy :find_categorias
	after_destroy :destroy_categorias_vazias

	has_many :categorizations, dependent: :destroy
	has_many :categorias, through: :categorizations, after_remove: :destroy_category_if_empty
	belongs_to :republica
	has_many :comentarios, dependent: :destroy

	accepts_nested_attributes_for :categorias, :reject_if => :all_blank

	attr_accessible :avaliacao, :endereco, :descricao, :email, :nome, :preco,
	:site, :tel1, :tel2
	attr_accessible :categorias_attributes, :categoria_ids

	validates :avaliacao, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
	validates :preco, numericality: {greater_than_or_equal_to: 0}, allow_blank: true
	validates_format_of :email, :with => /^\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i, message: 'Email inválido', allow_blank: true
	validates :nome, presence: true
	validates :descricao, presence: true, length: {minimum: 30, maximum: 500}
	validates_format_of :site, :with => URI::regexp(%w(http https)), message: "Por favor, insira o link completo, com http(s).", allow_blank: true
	validates :tel1, presence: {message: "Pelo menos um número deve estar presente."}

	validate :has_a_category
	validate :max_of_3_categories

	delegate :check_categoria_empty, to: :categorias

	def any_new_categorias?
		self.categorias.each do |cat|
			if cat.new_record?
				return true
			end
		end
		false
	end

	def destroy_category_if_empty(categoria)
		if categoria.servicos.count.zero?
			categoria.destroy
		end
	end


	private

	def find_categorias
		@categorias = self.categorias
	end

	def destroy_categorias_vazias
		@categorias.each do |cat|
			cat.destroy if cat.servicos.count.zero?
		end  
	end

	def downcase_site
		self.site.downcase! if self.site.present?
	end

	def titleize_endereco
		if self.endereco?
			self.endereco = self.endereco.titleize
		end
	end

	def has_a_category
		if self.categorias.blank?
			self.errors.add(:base, "Você deve selecionar uma categoria ou criar uma nova.")
		end		
	end

	def max_of_3_categories
		if self.categorias.length > 3
			self.errors.add(:base, "Você só pode selecionar no máximo 3 categorias.")
		end		
	end

end

app/controllers/admin/servicos_controller.rb
#encoding: utf-8

class Admin::ServicosController < AdminController

	def index
		@servicos_header = true

		if params[:categoria].present?
			@servicos = Servico.includes(:categorias).where('categorias.nome = ?', params[:categoria]).includes(:republica).order('avaliacao desc').page(params[:page])
		else
			@servicos = Servico.includes(:categorias).includes(:republica).order('avaliacao desc').page(params[:page])
		end

		if params[:republica] == 'true'
			@servicos = @servicos.where(republica_id: current_republica.id)
		end

		@categorias = Categoria.order('nome')


		respond_to do |format|
			format.html 
			format.js
		end
	end

	def edit
		@servico = Servico.find(params[:id])

		respond_to do |format|
			format.html 
		end
	end

	def update
		@servico = Servico.find(params[:id])

		respond_to do |format|
			if @servico.update_attributes(params[:servico])
				format.html { redirect_to admin_servicos_path, notice: 'Serviço atualizado.' }
			else
				format.html { render 'edit'  }
			end
		end
	end

	def destroy
		@servico = Servico.find(params[:id])

		respond_to do |format|
			if @servico.destroy
				flash[:notice] = "Serviço deletado!"
				format.html { redirect_to admin_servicos_path }
			else
				flash[:notice] = "Serviço não pode ser deletado."
				format.html { redirect_to admin_servicos_path }
			end
		end
	end

end

app/controllers/servicos_controller.rb
#encoding: utf-8

class ServicosController < RepublicaController
	load_and_authorize_resource

	def index
		@servicos_header = true

		if params[:categoria].present?
			@servicos = Servico.includes(:categorias).where('categorias.nome = ?', params[:categoria]).includes(:republica).order('avaliacao desc').page(params[:page])
		else
			@servicos = Servico.includes(:categorias).includes(:republica).order('avaliacao desc').page(params[:page])
		end

		if params[:republica] == 'true'
			@servicos = @servicos.where(republica_id: current_republica.id)
		end

		@categorias = Categoria.order('nome')


		respond_to do |format|
			format.html 
			format.js
		end
	end

	def new
		@republica = current_republica
		@servico = @republica.servicos.build
		@categoria = @servico.categorias.build

		respond_to do |format|
			format.html 
		end
	end

	def create
		@republica = current_republica
		@servico = @republica.servicos.build(params[:servico])
		@servico.categorias.each do |cat|
			cat.republica = current_republica
		end

		respond_to do |format|
			if @servico.save
				format.html { redirect_to servicos_path, notice: 'Serviço criado com sucesso.' }
			else
				format.html { render action: "new" }
			end
		end
	end

	def edit
		@servico = Servico.find(params[:id])

		respond_to do |format|
			format.html 
		end
	end

	def update
		@servico = Servico.find(params[:id])

		respond_to do |format|
			if @servico.update_attributes(params[:servico])
				format.html { redirect_to servicos_path, notice: 'Serviço atualizado.' }
			else
				format.html { render 'edit'  }
			end
		end
	end

	def destroy
		@servico = Servico.find(params[:id])

		respond_to do |format|
			if @servico.destroy
				flash[:notice] = "Serviço deletado!"
				format.html { redirect_to servicos_path }
			else
				flash[:notice] = "Serviço não pode ser deletado."
				format.html { redirect_to servicos_path }
			end
		end
	end

end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/admin/servicos/_servicos_boxes.html.erb
<% @servicos.each do |servico| %>
<div class='content-box content-box-for-servico'>
	<div class='content'>
		<h2><%= servico.nome %></h2>

		<% if servico.endereco? %>
		<p><b>Endereço:</b> <%= servico.endereco %></p>
		<% end %>

		<% if servico.preco? %>
		<p><b>Preço médio:</b> R$<%= servico.preco %></p>
		<% end %>

		<% if servico.descricao? %>
		<p><%= servico.descricao %></p>
		<% end %>

		<% if servico.tel1? %>
		<p><i class='fa fa-phone'></i> <%= servico.tel1 %></p>
		<% end %>

		<% if servico.tel2? %>
		<p><i class='fa fa-phone'></i> <%= servico.tel2 %></p>
		<% end %>

		<% if servico.email? %>
		<p><i class='fa fa-envelope'></i> <%= servico.email %></p>
		<% end %>

		<% if servico.site? %>
		<p><i class='fa fa-globe'></i> <%= servico.site %></p>
		<% end %>


		<div class='avaliacao-stars'>
			<% servico.avaliacao.times do %>
			<i class='fa fa-star'></i>
			<% end %>
			<% (5 - servico.avaliacao).times do %>
			<i class='fa fa-star-o'></i>
			<% end %>
		</div>

		<div class='categoria-tags'>
			<% servico.categorias.each do |cat| %>
			<p class='label label-inverse'><%= cat.nome %></p>
			<% end %>
		</div>
		<div class='servico-admin-action'>
			<%= link_to 'Editar', edit_admin_servico_path(servico) %> |
			<%= link_to 'Deletar', admin_servico_path(servico), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'red' %>
		</div>
		<p class='servico-edit'>Recomendação: <%= servico.republica.nome %></p>
	</div>
</div>
<%= link_to "<i class='fa fa-comments'></i> #{servico.comentarios.count}".html_safe, admin_servico_comentarios_path(servico), remote: true, class: "servico-#{servico.id}-comment-link comentarios-link nav-btn nav-btn-small" %>
<div class='servico-<%= servico.id %> comentarios'></div>
<% end %>
<p><%= will_paginate @servicos %></p>

app/views/admin/servicos/edit.html.erb
  <div class='content-box center-form'>
   <%= simple_nested_form_for @servico, html: {novalidate: 'novalidate'} do |f| %>
   <%= f.error_notification %>
   <%= display_base_errors @servico %>

   <fieldset>
    <legend>Editar Serviço</legend>
    <%= f.input :nome, label: false, placeholder: 'Nome da Pessoa ou Empresa', input_html: { class: 'input-xxlarge'} %>
    <%= f.input :endereco, label: false, placeholder: 'Endereço (opcional)', input_html: { class: 'input-xxlarge'}  %>
    <%= f.input :descricao, label: false, placeholder: 'Descrição', input_html: { class: 'input-xxlarge', rows: 10} %>
    <%= f.input :preco, label: false, placeholder: 'Preço Médio (opcional)' %>
    Avaliação
      <%= f.input :avaliacao, as: :radio_buttons, collection:[1,2,3,4,5] ,label: false, placeholder: 'Avaliação (1-5)', :item_wrapper_class => 'inline' %>
  </fieldset>

  <fieldset>
    <legend>Categoria</legend>

    <%= f.association :categorias, label: false, label_method: :nome, placeholder: 'Categoria', input_html: { class: 'input-xxlarge chz-categories'} %>

  </fieldset>

  <fieldset>
    <legend>Contatos</legend>

    <%= f.input :tel1, :wrapper => :prepend, label: false do %>
    <span class="add-on"><i class="fa fa-phone"></i></span><%= f.input_field :tel1, placeholder: "Telefone 1", class: 'celular' %>
    <% end %>

    <%= f.input :tel2, :wrapper => :prepend, label: false do %>
    <span class="add-on"><i class="fa fa-phone"></i></span><%= f.input_field :tel2, placeholder: "Telefone 2 (opcional)", class: 'celular' %>
    <% end %>

    <%= f.input :site, :wrapper => :prepend, label: false do %>
    <span class="add-on"><i class="fa fa-globe"></i></span><%= f.input_field :site, placeholder: "Site (opcional)" %>
    <% end %>

    <%= f.input :email, :wrapper => :prepend, label: false do %>
    <span class="add-on"><i class="fa fa-envelope"></i></span><%= f.input_field :email, placeholder: "Email (opcional)" %>
    <% end %>
  </fieldset>

  <div class="form-actions">
    <%= f.submit 'Editar', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', admin_servicos_path, class: 'btn' %>
  </div>


  <% end %>
</div>

app/views/admin/servicos/index.html.erb
<div class='row-fluid'>

	<div class='span4'>
		<div class='content-box categories-menu'>
			<%= link_to "Todas", admin_servicos_path, remote: true, class: 'nav-btn nav-btn-a nav-btn-small' %><h3>Categorias</h3>

			<% @categorias.each do |cat| %>
			<%= link_to cat.nome, admin_servicos_path(categoria: cat.nome), remote: true, class: 'nav-btn nav-btn-a nav-btn-small' %>
			<% end %>
		</div>
	</div>

	<div class='span8' id='servicos'>
		<%= render 'servicos_boxes' %>
	</div>

</div>

app/views/admin/servicos/index.js.erb
$("#servicos").html("<%=j render 'servicos_boxes' %>");
$(".pagination a").attr('data-remote', true);